In [1]:
import pandas as pd

In [2]:
df_test = pd.read_pickle('processed_data/prompts_test_embedding.pkl')

In [3]:
df_test.head()

Unnamed: 0  userId                                     test_movie_ids  \
0           0      87                         [1127, 6537, 72998, 79132]   
1           1      91  [590, 1619, 2324, 2628, 3481, 4022, 5378, 6870...   
2           2     225            [318, 8965, 47997, 60074, 60516, 65567]   
3           3     235                  [253, 4878, 31658, 57669, 122916]   
4           4     264  [178, 1297, 1653, 1735, 1747, 2169, 2864, 2888...   

                                              prompt  \
0  Pertend you are an expert recommender system. ...   
1  Pertend you are an expert recommender system. ...   
2  Pertend you are an expert recommender system. ...   
3  Pertend you are an expert recommender system. ...   
4  Pertend you are an expert recommender system. ...   

                                              vector  
0  [0.8050304, 0.5533147, 1.1143543, 0.24569008, ...  
1  [0.7123839, 0.50857514, 0.39143103, -0.3553590...  
2  [0.8050304, 0.5533147, 1.1143543, 0.24569008, ...  
3  [0.8050304, 0.5533147, 1.1143543, 0.24569008, ...  
4  [1.0498487, 0.35182106, 0.4857978, -0.44173834...

In [4]:
overviews = pd.read_pickle('processed_data/overviews_embedding.pkl')

In [5]:
overviews['vector'].to_numpy()

array([array([-0.14776279, -1.5611103 , -0.42982313, ...,  0.01729836,
               0.6139444 ,  0.4318419 ], dtype=float32)               ,
       array([ 0.7095556 , -0.75874114,  0.698982  , ...,  0.24948362,
              -0.7665281 ,  0.1422975 ], dtype=float32)               ,
       array([ 1.0267535 , -1.5537759 , -0.32268935, ..., -0.1445212 ,
              -0.20543224,  0.08687826], dtype=float32)               ,
       ...,
       array([ 0.93424237, -1.0832853 ,  0.23808132, ..., -0.2294382 ,
               0.90845895, -0.7432756 ], dtype=float32)               ,
       array([ 2.3644342 , -2.0513694 ,  0.84476185, ..., -1.1633662 ,
               0.5111976 , -0.22958137], dtype=float32)               ,
       array([ 1.0479237 , -0.9827712 , -0.16314815, ..., -0.59797275,
               1.0594771 , -0.8171304 ], dtype=float32)               ],
      dtype=object)

In [13]:
df_test[df_test['userId'] == 235]['vector'].iloc[0]

array([ 0.8050304 ,  0.5533147 ,  1.1143543 , ..., -0.8900344 ,
       -0.65438426, -0.3813841 ], dtype=float32)

In [14]:
from sklearn.neighbors import NearestNeighbors

knn = NearestNeighbors(n_neighbors=10, algorithm='auto')
knn.fit(overviews['vector'].to_numpy().tolist())

def get_neighbors_test(user_id):
    vector = df_test[df_test['userId'] == user_id]['vector'].iloc[0]
    return knn.kneighbors([vector], 10, return_distance=False)

In [15]:
df_test['vector'][0]

array([ 0.8050304 ,  0.5533147 ,  1.1143543 , ..., -0.8900344 ,
       -0.65438426, -0.3813841 ], dtype=float32)

In [36]:
knn.kneighbors([df_test['vector'][1]], 10, return_distance=False)[0]

array([19715, 19599, 42671, 22620, 13076,  4041, 26680,  1013, 31768,
       31056], dtype=int64)

In [29]:
df_test['test_movie_ids'][1]

'[590, 1619, 2324, 2628, 3481, 4022, 5378, 6870, 8207, 8958]'

In [28]:
overviews['original_title'][4041]

'Avalon'

In [41]:
def recall(test_movie_ids, retrieved_ids):
    n = len(test_movie_ids)
    correct = 0
    for idx in retrieved_ids:
        if idx in test_movie_ids:
            correct += 1
    return correct / n

In [39]:
get_neighbors_test(87)

array([[41274, 10409, 43934, 41557, 25735, 44181, 31708, 14140,   637,
         5256]], dtype=int64)

In [49]:
s = 0
for id, row in df_test.iterrows():
    user_id = row['userId']
    neighbors = get_neighbors_test(user_id)[0]
    watched = row['test_movie_ids']
    rec = recall(watched, neighbors)
    print(rec)
    s += rec
print(s / len(df_test))

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


KeyboardInterrupt: 

In [48]:
import ast
df_test['test_movie_ids'] = df_test['test_movie_ids'].apply(ast.literal_eval)

In [52]:
overviews_common = pd.read_csv('processed_data/overviews_common.csv')
common_ids = overviews_common['movieId'].unique()

In [53]:
smaller_overviews = overviews[overviews['movieId'].isin(common_ids)]

In [54]:
len(overviews)

44571

In [55]:
len(smaller_overviews)

14550

In [56]:
knn2 = NearestNeighbors(n_neighbors=10, algorithm='auto')
knn2.fit(smaller_overviews['vector'].to_numpy().tolist())
def get_neighbors_test2(user_id):
    vector = df_test[df_test['userId'] == user_id]['vector'].iloc[0]
    return knn2.kneighbors([vector], 10, return_distance=False)

In [57]:
s = 0
for id, row in df_test.iterrows():
    user_id = row['userId']
    neighbors = get_neighbors_test(user_id)[0]
    watched = row['test_movie_ids']
    rec = recall(watched, neighbors)
    print(rec)
    s += rec
print(s / len(df_test))

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


KeyboardInterrupt: 