In [1]:
import pandas as pd

In [9]:
df = pd.read_csv('processed_data/prompts_test_embedding.csv')

In [30]:
df.head()

Unnamed: 0.1  Unnamed: 0  userId  \
0             0           0      87   
1             1           1      91   
2             2           2     225   
3             3           3     235   
4             4           4     264   

                                      test_movie_ids  \
0                         [1127, 6537, 72998, 79132]   
1  [590, 1619, 2324, 2628, 3481, 4022, 5378, 6870...   
2            [318, 8965, 47997, 60074, 60516, 65567]   
3                  [253, 4878, 31658, 57669, 122916]   
4  [178, 1297, 1653, 1735, 1747, 2169, 2864, 2888...   

                                              prompt  \
0  Pertend you are an expert recommender system. ...   
1  Pertend you are an expert recommender system. ...   
2  Pertend you are an expert recommender system. ...   
3  Pertend you are an expert recommender system. ...   
4  Pertend you are an expert recommender system. ...   

                                              vector  
0  [ 0.8050309   0.5533149   1.1143546  ... -0.89...  
1  [ 0.7123806   0.50857526  0.39143145 ... -0.39...  
2  [ 0.8050309   0.5533149   1.1143546  ... -0.89...  
3  [ 0.8050309   0.5533149   1.1143546  ... -0.89...  
4  [ 1.0498489   0.35182142  0.4857985  ... -0.60...

In [5]:
overviews = pd.read_pickle('processed_data/overviews_embedding.pkl')

In [13]:
overviews['vector'].to_numpy()

array([array([-0.14776279, -1.5611103 , -0.42982313, ...,  0.01729836,
               0.6139444 ,  0.4318419 ], dtype=float32)               ,
       array([ 0.7095556 , -0.75874114,  0.698982  , ...,  0.24948362,
              -0.7665281 ,  0.1422975 ], dtype=float32)               ,
       array([ 1.0267535 , -1.5537759 , -0.32268935, ..., -0.1445212 ,
              -0.20543224,  0.08687826], dtype=float32)               ,
       ...,
       array([ 0.93424237, -1.0832853 ,  0.23808132, ..., -0.2294382 ,
               0.90845895, -0.7432756 ], dtype=float32)               ,
       array([ 2.3644342 , -2.0513694 ,  0.84476185, ..., -1.1633662 ,
               0.5111976 , -0.22958137], dtype=float32)               ,
       array([ 1.0479237 , -0.9827712 , -0.16314815, ..., -0.59797275,
               1.0594771 , -0.8171304 ], dtype=float32)               ],
      dtype=object)

In [16]:
overviews['vector'].to_numpy().tolist()

[array([-0.14776279, -1.5611103 , -0.42982313, ...,  0.01729836,
         0.6139444 ,  0.4318419 ], dtype=float32),
 array([ 0.7095556 , -0.75874114,  0.698982  , ...,  0.24948362,
        -0.7665281 ,  0.1422975 ], dtype=float32),
 array([ 1.0267535 , -1.5537759 , -0.32268935, ..., -0.1445212 ,
        -0.20543224,  0.08687826], dtype=float32),
 array([ 1.7860366 , -0.56084675, -1.0011823 , ...,  0.00276888,
        -0.06187086,  0.13662092], dtype=float32),
 array([ 1.430807  , -0.8232753 ,  0.8106583 , ...,  0.10747589,
        -0.26851588, -0.09499387], dtype=float32),
 array([ 0.13531673, -1.1151783 ,  0.29012454, ..., -0.02684133,
        -0.4897161 ,  0.34875923], dtype=float32),
 array([ 1.7890756 , -0.7508465 ,  0.16534813, ...,  0.5876769 ,
         0.22396907,  0.3963609 ], dtype=float32),
 array([ 1.3412374 , -1.1996274 ,  0.744597  , ..., -0.32526088,
        -0.72039646, -0.20541228], dtype=float32),
 array([ 1.3810161 , -0.28632525, -0.02050165, ..., -0.24910773,
       

In [15]:
from sklearn.neighbors import NearestNeighbors

knn = NearestNeighbors(n_neighbors=10, algorithm='auto')
knn.fit(overviews['vector'].to_numpy().tolist())

def get_neighbors_test(user_id):
    vector = overviews[overviews['userId'] == user_id]['vector'].uniques()[0]
    return knn.kneighbors([vector], 10, return_distance=False)

In [36]:
knn.kneighbors([overviews['vector'][1]], 10, return_distance=False)

array([[    1, 10899, 15113, 11513,  2478, 34640,  8098, 10570, 13317,
         4552]], dtype=int64)

In [37]:
overviews['original_title'][1]

'Jumanji'

In [40]:
overviews['original_title'][15113]

'Κυνόδοντας'

In [4]:
def recall(test_movie_ids, retrieved_ids):
    n = len(test_movie_ids)
    correct = 0
    for idx in retrieved_ids:
        if idx in test_movie_ids:
            correct += 1
    return correct / n